const menu = [
  {
    id: 1,
    type: "Lunch",
    name: "ayam taliwang",
    desc: "Spicy grilled chicken originates from the island of Lombok. Using free range chickens or sometimes spring chickens",
    price: "2.67",
    img: "ayam-taliwang.jpg",
  },
  {
    id: 2,
    type: "Beverages",
    name: "Bajigur",
    desc: "A traditional Sundanese drink. It is made from palm sugar, coconut milk, ginger, and Vanilla essence",
    price: "0.84",
    img: "bajigur.jpg",
  },
  {
    id: 3,
    type: "Beverages",
    name: "Bandrek",
    desc: "Made from ginger, lemongrass, pepper, palm sugar, salt, cloves, cinnamon, and pandan leaves.",
    price: "0.84",
    img: "bandrek.jpg",
  },
  {
    id: 4,
    type: "Breakfast",
    name: "Bubur Ayam",
    desc: "Rice porridge, a bowl comes topped with shredded chicken, along with skewers of fried chicken heart and other organs",
    price: "1.41",
    img: "bubur-ayam.jpg",
  },
  {
    id: 5,
    type: "Lunch",
    name: "Coto Makasar",
    desc: "Dark beef soup or stew originally from the foodie city Makassar, with beef and organs",
    price: "1.76",
    img: "cotto-makassar.jpg",
  },

  {
    id: 6,
    type: "Breakfast",
    name: "Gado-gado",
    desc: "Vegetables and compressed rice salad, made with peanut sauce (or cashew nut sauce) dressing",
    price: "2.11",
    img: "gado-gado.jpg",
  },
  {
    id: 7,
    type: "Breakfast",
    name: "Ketoprak",
    desc: "Fried tofu, chopped it with some bean sprouts, peanut sauce, and a fried egg.",
    price: "2.11",
    img: "ketoprak.jpg",
  },
  {
    id: 8,
    type: "Breakfast",
    name: "Martabak",
    desc: "Sweet waffle with butter, sugar, cheese, chocolate, or a variety of other fillings of choice",
    price: "1.83",
    img: "martabak.jpg",
  },
  {
    id: 9,
    type: "Lunch",
    name: "Nasi Goreng",
    desc: "rice is stir fried, seasoned with crushed chili sambal and garlic, mixed with kecap manis",
    price: "3.58",
    img: "nasi-goreng.jpg",
  },
  {
    id: 10,
    type: "Lunch",
    name: "Duck Rica rica",
    desc: "Fried duck with dry sauce, teeming with red chilies, shallots, and tomatoes.",
    price: "2.95",
    img: "rica-rica.jpg",
  },
  {
    id: 11,
    type: "Lunch",
    name: "Chicken Satay",
    desc: "Chicken marinated in sweet kecap manis soy sauce, grilled on an extremely hot charcoal fire",
    price: "2.46",
    img: "sate-ayam.jpg",
  },
  {
    id: 12,
    type: "Beverages",
    name: "Sekoteng",
    desc: "Hot ginger water filled with sweet mung beans, peanuts, and chunks of bread",
    price: "0.9",
    img: "sekoteng.jpg",
  },
  {
    id: 13,
    type: "Lunch",
    name: "Sayur Asem",
    desc: "sour tamarind soup, with meat stock and a mixture of corn, chayote, and water morning glory",
    price: "1.05",
    img: "sayur-asem.jpg",
  },
  {
    id: 14,
    type: "Breakfast",
    name: "Siomay",
    desc: "Fish Dumplings  served with a sweet and savory peanut sauce and some sambal",
    price: "1.05",
    img: "siomay.jpg",
  },
];
export default menu;
